"""is blocked by avatar

Revision ID: 5e0ee618658d
Revises: 14573cba8f4c
Create Date: 2022-01-07 20:16:11.544493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0ee618658d'
down_revision = '14573cba8f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_blocked_by_avatar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_blocked_by_avatar')
    # ### end Alembic commands ###
