"""admin and new relationships

Revision ID: 79b040f84e30
Revises: 5e0ee618658d
Create Date: 2022-01-15 10:13:46.788582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b040f84e30'
down_revision = '5e0ee618658d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('personal_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('is_moderation_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_admin_id'), 'chat', ['admin_id'], unique=False)
    op.add_column('message', sa.Column('message_metadata_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'message', 'message_metadata', ['message_metadata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'message_metadata_id')
    op.drop_index(op.f('ix_chat_admin_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_table('admin')
    # ### end Alembic commands ###
