"""initial

Revision ID: a8a2108b7b78
Revises: 
Create Date: 2022-01-23 20:11:34.807081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a2108b7b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('personal_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('message_metadata_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['message_metadata_id'], ['message_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('msg_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_blocked_by_avatar', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    #sa.ForeignKeyConstraint(['msg_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # иначе не накатывается миграшка
    op.create_foreign_key(None, 'message', 'message_metadata', [
                          'message_metadata_id'], ['id'])
    op.create_foreign_key(None, 'message_metadata',
                          'message', ['msg_id'], ['id'])

    op.create_index(op.f('ix_message_metadata_msg_id'), 'message_metadata', ['msg_id'], unique=False)
    op.create_index(op.f('ix_message_metadata_tg_msg_id'), 'message_metadata', ['tg_msg_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('is_moderation_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_admin_id'), 'group', ['admin_id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_metadata_id', sa.BigInteger(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_metadata_id'], ['message_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_link'), 'link', ['link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_link'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_group_admin_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_message_metadata_tg_msg_id'), table_name='message_metadata')
    op.drop_index(op.f('ix_message_metadata_msg_id'), table_name='message_metadata')
    op.drop_table('message_metadata')
    op.drop_table('message')
    op.drop_table('admin')
    # ### end Alembic commands ###
