"""repositories

Revision ID: b3613053e5d4
Revises: 1ecf65386ba7
Create Date: 2021-12-27 10:35:53.222987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3613053e5d4'
down_revision = '1ecf65386ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_metadata', sa.Column('tg_msg_id', sa.Integer(), nullable=True))
    op.add_column('message_metadata', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_message_metadata_tg_msg_id'), 'message_metadata', ['tg_msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_metadata_tg_msg_id'), table_name='message_metadata')
    op.drop_column('message_metadata', 'is_deleted')
    op.drop_column('message_metadata', 'tg_msg_id')
    # ### end Alembic commands ###
