DATABASE:
  POSTGRE_HOST: database-nsfw-prod.cdlt3gh42ady.eu-west-2.rds.amazonaws.com
  POSTGRE_USER: nsfw_admin
  POSTGRE_PASSWORD: aHR!##9887ASDsda
  POSTGRE_NAME: NSFWBotDatabase
  POSTGRE_PORT: 5444
