name: 'CI/CD Pipeline'

on:
  push:
    branches: [ main ]
jobs:
  ci-classifier-service:
    runs-on: ubuntu-latest

    steps:
    # Step 1
    - uses: actions/checkout@v2

    # Step 2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
        architecture: "amd64"
    # Step 3
    - name: Install Python Virtual Environment
      run: pip3 install virtualenv
      
    # Step 4
    - name:  Setup Virtual env
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    # Step 5
    - name: Activate and Install Depencies into Virtual env
      run: python -m venv venv && source venv/bin/activate &&
        pip3 install -r NSFW_Classifier_Service/requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    # Step 6
    #shoul be tests

    # Step 7
    - name: Create Zipfile of Dependencies
      run: |
        cd ./venv/lib/python3.7/site-packages
        zip -r9 ../../../../nsfw-service.zip .
    
    # Step 8
    - name: Add App to Zip file
      run: cd ./NSFW_Classifier_Service && zip -g ../nsfw-service.zip -r .
    
    # Step 9
    - name: Upload zip file artifact
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: nsfw-service.zip

  #cd:

