name: 'CI/CD Pipeline for NSFW Service'

on:
  push:
    branches: [ main ]
    paths: 
      - 'NSFW_Classifier_Service'

  pull_request:
    branches: [ main ]
    paths: 
      - 'NSFW_Classifier_Service'
      
jobs:
  ci-classifier-service:
    runs-on: ubuntu-latest

    steps:
    # Step 1
    - uses: actions/checkout@v2

    # Step 2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7.12"
        architecture: "x64"
    # Step 3
    - name: Install Python Virtual Environment
      run: pip3 install virtualenv
      
    # Step 4
    - name:  Setup Virtual env
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    # Step 5
    - name: Activate and Install Depencies into Virtual env
      run: python -m venv venv && source venv/bin/activate &&
        pip3 install -r NSFW_Classifier_Service/requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    # Step 6
    #shoul be tests

    # Step 7
    - name: Create Zipfile of Dependencies
      run: |
        cd ./venv/lib/python3.7/site-packages
        zip -r9 ../../../../nsfw-service.zip .
    
    # Step 8
    - name: Add App to Zip file
      run: cd ./NSFW_Classifier_Service && zip -g ../nsfw-service.zip -r .
    
    # Step 9
    - name: Upload zip file artifact
      uses: actions/upload-artifact@v2
      with:
        name: nsfw_service
        path: nsfw-service.zip

  cd-classifier-service:
    runs-on: ubuntu-latest
    needs: [ ci-classifier-service ]
    if: github.ref == 'refs/heads/main'
    steps:

    # Step 1
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    # Step 2
    - name: Download Service Zip for Lambda
      uses: actions/download-artifact@v2
      with:
        name: nsfw_service

    # Step 3
    - name: Upload to S3
      run: aws s3 cp nsfw-service.zip s3://nsfw-bucket-prod/nsfw-service.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    # Step 4
    - name: Deploy new Lambda
      run: aws lambda update-function-code --function-name runNSFWDetection --s3-bucket nsfw-bucket-prod --s3-key nsfw-service.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
